model:
  cldm:
    target: diffbir.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  diffusion:
    target: diffbir.model.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000

guidance:
  target: diffbir.utils.cond_fn.WeightedSSIMGuidance
  params:
    # guidance strength (baseline AlignOp configuration)
    scale: 0.1
    t_start: 601
    t_stop: -1
    space: "rgb"
    repeat: 1

inference:
  # tau and omega are proportions of the total steps, i.e., 1000 (baseline AlignOp)
  tau: 0.8
  omega: 0.6
  
  # Model weights paths
  sd_path: 'weights/v2-1_512-ema-pruned.ckpt'
  controlnet_path: 'experiment/stage2_ycbcr_hcycle/checkpoints/0020000.pt'
  
  # Input and output paths for RTTS evaluation
  image_folder: '../HCD-YC/datasets/RTTS/JPEGImages'
  result_folder: 'evaluation_outputs/baseline_stage2_results'
  
  # Image processing settings for evaluation
  max_image_size: 512
  resize_shorter_edge: 384
  padding_multiple: 64 