model:
  cldm:
    target: diffbir.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        target: diffbir.model.controlnet.YCbCrControlNet
        params:
          use_checkpoint: True
          image_size: 32 # unused
          in_channels: 4
          hint_channels: 4
          model_channels: 320
          attention_resolutions: [ 4, 2, 1 ]
          num_res_blocks: 2
          channel_mult: [ 1, 2, 4, 4 ]
          num_head_channels: 64 # need to fix for flash-attn
          use_spatial_transformer: True
          use_linear_in_transformer: True
          transformer_depth: 1
          context_dim: 1024
          legacy: False
          ycbcr_fusion: True

  diffusion:
    target: diffbir.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000

dataset:
  train:
    target: datasets.HybridTrainingData
    params:
      syn_folder: "datasets/RIDCP/"
      real_folder: "datasets/URHI/"
      crop_size: 256
      p: 0.3


train:
  # pretrained sd path
  sd_path: 'weights/v2-1_512-ema-pruned.ckpt'
  # experiment directory path
  exp_dir: './experiment/stage1_ycbcr_hcycle/'
  learning_rate: 5e-5
  batch_size: 64
  num_workers: 24
  train_steps: 5000
  log_every: 100
  ckpt_every: 1000
  image_every: 1000
  resume: ~
  
  # hierarchical cycle consistency settings
  cycle_start_step: 500  # start applying cycle consistency loss
  cycle_max_step: 2000   # cycle loss weight reaches maximum
  cycle_weight: 0.5      # hierarchical cycle consistency loss weight
  asym_weight: 0.3       # asymmetric cycle loss weight
  
  # hierarchical loss weights
  pixel_weight: 1.0      # pixel level loss weight
  feature_weight: 1.0    # feature level loss weight
  semantic_weight: 0.5   # semantic level loss weight
  region_weight: 0.2     # region-aware loss weight
  adaptive_weight: True  # whether to use adaptive weights
  use_dcp: True          # whether to use dark channel prior
  
  # cycle consistency direction weights
  forward_weight: 0.7    # forward cycle weight (clear->hazy->clear)
  backward_weight: 0.3   # backward cycle weight (hazy->clear->hazy)